name: Version Consistency Check

on:
  push:
    branches: 
      - 'release/*'
  pull_request:
    branches: 
      - 'release/*'

jobs:
  version-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
    - name: Install jq
      run: |
        sudo apt-get update && sudo apt-get install -y jq

    - name: Make version check script executable
      run: chmod +x scripts/compare-versions.sh

    - name: Run version consistency check
      run: ./scripts/compare-versions.sh
